
export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_ADMIN_SUCCESS = "AUTH_ADMIN_SUCCESS";
export const AUTH_POLICE_SUCCESS = "AUTH_POLICE_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_ADMIN_REQUEST = "AUTH_ADMIN_REQUEST";
export const AUTH_POLICE_REQUEST = "AUTH_POLICE_REQUEST";