export const USER_REQUEST = "USER_REQUEST";
export const USER_ADMIN_REQUEST = "USER_ADMIN_REQUEST";
export const USER_POLICE_REQUEST = "USER_POLICE_REQUEST";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_ERROR = "USER_ERROR";